//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BespokedBikesTimHawkins.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public System.Guid SalesId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid SalespersonId { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.DateTime SalesDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Salesperson Salesperson { get; set; }
    }
}
